## HIDING FUTURE WORDS WITH CAUSAL ATTENTION

<div class="alert alert-block alert-success">

Let's work with the attention scores and weights from the previous section to code the causal attention mechanism.
    
</div>

<div class="alert alert-block alert-success">

In the first step illustrated in Figure 3.20, we compute the attention weights using the
softmax function as we have done in previous sections:    
</div>


<div class="alert alert-block alert-info">

Reuse the query and key weight matrices of the SelfAttention_v2 object from the previous section for
convenience
    
</div>

In [ ]:
import torch

inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

In [8]:
import torch
import torch.nn as nn

class SelfAttention_v2(nn.Module):

    def __init__(self, d_in, d_out, qkv_bias=False):
        super().__init__()
        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key   = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)

    def forward(self, x):
        keys = self.W_key(x)
        queries = self.W_query(x)
        values = self.W_value(x)

        attn_scores = queries @ keys.T
        attn_weights = torch.softmax(attn_scores / keys.shape[-1]**0.5, dim=-1)

        context_vec = attn_weights @ values
        return context_vec

d_in = 3
d_out = 6

sa_v2 = SelfAttention_v2(d_in, d_out)

In [9]:
queries = sa_v2.W_query(inputs) # A
keys = sa_v2.W_key(inputs)

attn_scores = queries @ keys.T

attn_weights = torch.softmax(attn_scores / keys.shape[-1]**0.5, dim=1)

print(attn_weights)

tensor([[0.1744, 0.1761, 0.1742, 0.1606, 0.1355, 0.1791],
        [0.1674, 0.1822, 0.1796, 0.1595, 0.1253, 0.1860],
        [0.1675, 0.1822, 0.1796, 0.1594, 0.1259, 0.1855],
        [0.1660, 0.1753, 0.1739, 0.1638, 0.1425, 0.1785],
        [0.1693, 0.1769, 0.1758, 0.1596, 0.1474, 0.1708],
        [0.1651, 0.1763, 0.1744, 0.1646, 0.1353, 0.1843]],
       grad_fn=<SoftmaxBackward0>)


<div class="alert alert-block alert-success">

We can now use PyTorch's tril function to create a mask
where the values above the diagonal are zero:

</div>

In [10]:
context_length = attn_scores.shape[0]

torch.ones(context_length, context_length)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [11]:
context_length = attn_scores.shape[0]
mask_simple = torch.tril(torch.ones(context_length, context_length))
print(mask_simple)

tensor([[1., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1.]])


<div class="alert alert-block alert-success">

Now, we can multiply this mask with the attention weights to zero out the values above the
diagonal:

</div>

In [12]:
masked_simple = attn_weights * mask_simple
print(masked_simple)

tensor([[0.1744, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1674, 0.1822, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1675, 0.1822, 0.1796, 0.0000, 0.0000, 0.0000],
        [0.1660, 0.1753, 0.1739, 0.1638, 0.0000, 0.0000],
        [0.1693, 0.1769, 0.1758, 0.1596, 0.1474, 0.0000],
        [0.1651, 0.1763, 0.1744, 0.1646, 0.1353, 0.1843]],
       grad_fn=<MulBackward0>)


<div class="alert alert-block alert-info">

As we can see, the elements above the diagonal are successfully zeroed out
    
</div>

<div class="alert alert-block alert-success">

The third step is to renormalize the attention weights to sum up to 1 again in
each row.

We can achieve this by dividing each element in each row by the sum in each
row:

</div>

In [13]:
row_sums = masked_simple.sum(dim=1, keepdim=True)
masked_simple_norm = masked_simple / row_sums
print(masked_simple_norm)

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4788, 0.5212, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3165, 0.3442, 0.3393, 0.0000, 0.0000, 0.0000],
        [0.2445, 0.2582, 0.2561, 0.2412, 0.0000, 0.0000],
        [0.2042, 0.2134, 0.2121, 0.1925, 0.1778, 0.0000],
        [0.1651, 0.1763, 0.1744, 0.1646, 0.1353, 0.1843]],
       grad_fn=<DivBackward0>)


<div class="alert alert-block alert-info">

The result is an attention weight matrix where the attention weights above the diagonal are
zeroed out and where the rows sum to 1.

</div>

<div class="alert alert-block alert-success">

While we could be technically done with implementing causal attention at this point, we can
take advantage of a mathematical property of the softmax function.

We can implement the computation of the masked attention weights more efficiently in fewer steps.

</div>

<div class="alert alert-block alert-success">

The softmax function converts its inputs into a probability distribution.

When negative
infinity values (-∞) are present in a row, the softmax function treats them as zero
probability.

(Mathematically, this is because e
-∞ approaches 0.)


We can implement this more efficient masking "trick" by creating a mask with 1's above
the diagonal and then replacing these 1's with negative infinity (-inf) values:

</div>

In [14]:
print(attn_scores)

tensor([[ 0.5470,  0.5700,  0.5444,  0.3443, -0.0708,  0.6124],
        [ 0.6617,  0.8694,  0.8335,  0.5434, -0.0479,  0.9201],
        [ 0.6619,  0.8674,  0.8321,  0.5405, -0.0385,  0.9116],
        [ 0.3279,  0.4611,  0.4410,  0.2950, -0.0456,  0.5048],
        [ 0.4803,  0.5879,  0.5729,  0.3358,  0.1414,  0.5021],
        [ 0.3512,  0.5124,  0.4854,  0.3431, -0.1375,  0.6205]],
       grad_fn=<MmBackward0>)


In [15]:
torch.triu(torch.ones(context_length, context_length))

tensor([[1., 1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 0., 1.]])

In [16]:
mask = torch.triu(torch.ones(context_length, context_length), diagonal=1)
print(mask)

tensor([[0., 1., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0.]])


In [17]:
mask = torch.triu(torch.ones(context_length, context_length), diagonal=1)
masked = attn_scores.masked_fill(mask.bool(), -torch.inf)
print(masked)

tensor([[ 0.5470,    -inf,    -inf,    -inf,    -inf,    -inf],
        [ 0.6617,  0.8694,    -inf,    -inf,    -inf,    -inf],
        [ 0.6619,  0.8674,  0.8321,    -inf,    -inf,    -inf],
        [ 0.3279,  0.4611,  0.4410,  0.2950,    -inf,    -inf],
        [ 0.4803,  0.5879,  0.5729,  0.3358,  0.1414,    -inf],
        [ 0.3512,  0.5124,  0.4854,  0.3431, -0.1375,  0.6205]],
       grad_fn=<MaskedFillBackward0>)


<div class="alert alert-block alert-success">

Now, all we need to do is apply the softmax function to these masked results, and we are
done.

</div>

In [19]:
attn_weights = torch.softmax(masked / keys.shape[-1]**0.5, dim=1)
print(attn_weights)

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4788, 0.5212, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3165, 0.3442, 0.3393, 0.0000, 0.0000, 0.0000],
        [0.2445, 0.2582, 0.2561, 0.2412, 0.0000, 0.0000],
        [0.2042, 0.2134, 0.2121, 0.1925, 0.1778, 0.0000],
        [0.1651, 0.1763, 0.1744, 0.1646, 0.1353, 0.1843]],
       grad_fn=<SoftmaxBackward0>)


<div class="alert alert-block alert-info">

As we can see based on the output, the values in each row sum to 1, and no further
normalization is necessary.

</div>

<div class="alert alert-block alert-warning">

Masking in Transformers sets scores for future tokens to a large negative value, making their influence in the softmax calculation effectively zero.

The softmax function then recalculates attention weights only among the unmasked tokens.

This process ensures no information leakage from masked tokens, focusing the model solely on the intended data.

</div>

<div class="alert alert-block alert-warning">

We could now use the modified attention weights to compute the context vectors via
context_vec = attn_weights @ values.

However, in the next section,
we first cover another minor tweak to the causal attention mechanism that is useful for
reducing overfitting when training LLMs.

</div>

### MASKING ADDITIONAL ATTENTION WEIGHTS WITH DROPOUT

<div class="alert alert-block alert-success">

In the following code example, we use a dropout rate of 50%, which means masking out
half of the attention weights.

When we train the GPT model in later chapters, we will use a
lower dropout rate, such as 0.1 or 0.2.
</div>

<div class="alert alert-block alert-success">

In the following code, we apply PyTorch's dropout implementation first to a 6×6 tensor
consisting of ones for illustration purposes:
</div>

In [20]:
example = torch.ones(6, 6) # B
print(example)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


In [21]:
torch.manual_seed(123)
dropout = torch.nn.Dropout(0.5) # A
example = torch.ones(6, 6) # B
print(dropout(example))

tensor([[2., 2., 2., 2., 2., 2.],
        [0., 2., 0., 0., 0., 0.],
        [0., 0., 2., 0., 2., 0.],
        [2., 2., 0., 0., 0., 2.],
        [2., 0., 0., 0., 0., 2.],
        [0., 2., 0., 0., 0., 0.]])


<div class="alert alert-block alert-info">

When applying dropout to an attention weight matrix with a rate of 50%, half of the
elements in the matrix are randomly set to zero.

To compensate for the reduction in active
elements, the values of the remaining elements in the matrix are scaled up by a factor of
1/0.5 =2.

This scaling is crucial to maintain the overall balance of the attention weights,
ensuring that the average influence of the attention mechanism remains consistent during
both the training and inference phases.
</div>

<div class="alert alert-block alert-success">

Now, let's apply dropout to the attention weight matrix itself:

</div>

In [22]:
torch.manual_seed(123)
print(dropout(attn_weights))

tensor([[2.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 1.0424, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.6786, 0.0000, 0.0000, 0.0000],
        [0.4890, 0.5164, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4084, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.3527, 0.0000, 0.0000, 0.0000, 0.0000]],
       grad_fn=<MulBackward0>)


<div class="alert alert-block alert-info">

As we can see above, the resulting attention weight matrix now has additional elements zeroed out and the
remaining ones rescaled.
    
</div>

<div class="alert alert-block alert-warning">

Having gained an understanding of causal attention and dropout masking, we will
develop a concise Python class in the following section.

This class is designed to facilitate
the efficient application of these two techniques.

</div>

### IMPLEMENTING A COMPACT CAUSAL ATTENTION CLASS

<div class="alert alert-block alert-success">

In this section, we will now incorporate the causal attention and dropout modifications into
the SelfAttention Python class we developed in section 3.4.

This class will then serve as a
template for developing multi-head attention in the upcoming section.

</div>

<div class="alert alert-block alert-success">

Before we begin, one more thing is to ensure that the code can handle batches
consisting of more than one input.

This will ensure that the CausalAttention class supports the batch
outputs produced by the data loader we implemented earlier.

</div>

<div class="alert alert-block alert-success">

For simplicity, to simulate such batch inputs, we duplicate the input text example:

</div>

<div class="alert alert-block alert-info">

 2 inputs with 6 tokens each, and each token has embedding dimension 3
    
</div>

In [23]:
inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

batch = torch.stack((inputs, inputs), dim=0)
print(batch.shape)

torch.Size([2, 6, 3])


<div class="alert alert-block alert-info">

This results in a 3D tensor consisting of 2 input texts with 6 tokens each, where each token
is a 3-dimensional embedding vector.
    
</div>

<div class="alert alert-block alert-success">

The following CausalAttention class is similar to the SelfAttention class we
implemented earlier, except that we now added the dropout and causal mask components
as highlighted in the following code.
    
</div>

<div class="alert alert-block alert-info">

Step 1: Compared to the previous SelfAttention_v1 class, we added a dropout layer.
    
Step 2: The register_buffer call is also a new addition (more information is provided in the following text).

Step 3:  We transpose dimensions 1 and 2, keeping the batch dimension at the first position (0).

Step 4: In PyTorch, operations with a trailing underscore are performed in-place, avoiding unnecessary memory
copies
    
</div>

In [24]:
class CausalAttention(nn.Module):

    def __init__(
        self,
        d_in,
        d_out,
        context_length,
        dropout,
        qkv_bias=False
    ):
        super().__init__()
        self.d_out = d_out
        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key   = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.dropout = nn.Dropout(dropout) # New
        self.register_buffer('mask', torch.triu(torch.ones(context_length, context_length), diagonal=1)) # New

    def forward(self, x):
        b, num_tokens, d_in = x.shape # New batch dimension b
        keys = self.W_key(x)
        queries = self.W_query(x)
        values = self.W_value(x)

        attn_scores = queries @ keys.transpose(1, 2) # Changed transpose
        attn_scores.masked_fill_(  # New, _ ops are in-place
            self.mask.bool()[:num_tokens, :num_tokens], -torch.inf
        )  # `:num_tokens` to account for cases where the number of tokens in the batch is smaller than the supported context_size
        attn_weights = torch.softmax(
            attn_scores / keys.shape[-1]**0.5, dim=-1
        )
        attn_weights = self.dropout(attn_weights) # New

        context_vec = attn_weights @ values
        return context_vec

<div class="alert alert-block alert-warning">

The use of register_buffer in
PyTorch is not strictly necessary for all use cases but offers several advantages here.

For
instance, when we use the CausalAttention class in our LLM, buffers are automatically
moved to the appropriate device (CPU or GPU) along with our model, which will be relevant
when training the LLM in future chapters.

This means we don't need to manually ensure
these tensors are on the same device as your model parameters, avoiding device mismatch
errors.

</div>

<div class="alert alert-block alert-success">

We can use the CausalAttention class as follows, similar to SelfAttention previously:
    
</div>

In [25]:
print(d_in)

3


In [26]:
print(d_out)

6


In [27]:
torch.manual_seed(123)
context_length = batch.shape[1]
ca = CausalAttention(d_in, d_out, context_length, 0.0)
context_vecs = ca(batch)
print("context_vecs.shape:", context_vecs.shape)

context_vecs.shape: torch.Size([2, 6, 6])


In [28]:
print(context_vecs)

tensor([[[-0.5967, -0.2754,  0.0189,  0.0752,  0.4566,  0.2729],
         [-0.6362, -0.2762,  0.2052,  0.0361,  0.5823,  0.3018],
         [-0.6500, -0.2736,  0.2695,  0.0220,  0.6279,  0.3108],
         [-0.5709, -0.2437,  0.2775,  0.0111,  0.5678,  0.2779],
         [-0.5475, -0.1987,  0.2400,  0.0087,  0.5555,  0.2520],
         [-0.5198, -0.2079,  0.2659,  0.0042,  0.5322,  0.2494]],

        [[-0.5967, -0.2754,  0.0189,  0.0752,  0.4566,  0.2729],
         [-0.6362, -0.2762,  0.2052,  0.0361,  0.5823,  0.3018],
         [-0.6500, -0.2736,  0.2695,  0.0220,  0.6279,  0.3108],
         [-0.5709, -0.2437,  0.2775,  0.0111,  0.5678,  0.2779],
         [-0.5475, -0.1987,  0.2400,  0.0087,  0.5555,  0.2520],
         [-0.5198, -0.2079,  0.2659,  0.0042,  0.5322,  0.2494]]],
       grad_fn=<UnsafeViewBackward0>)


In [29]:
import torch
import torch.nn as nn

class CausalAttention(nn.Module):

    def __init__(self, d_in, d_out, context_length, dropout, qkv_bias=False):
        super().__init__()
        self.d_out = d_out
        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key   = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.dropout = nn.Dropout(dropout) # New
        self.register_buffer('mask', torch.triu(torch.ones(context_length, context_length), diagonal=1)) # New

    def forward(self, x):
        b, num_tokens, d_in = x.shape # New batch dimension b
        keys = self.W_key(x)
        queries = self.W_query(x)
        values = self.W_value(x)

        attn_scores = queries @ keys.transpose(1, 2) # Changed transpose
        attn_scores.masked_fill_(  # New, _ ops are in-place
            self.mask.bool()[:num_tokens, :num_tokens], -torch.inf)

        attn_weights = torch.softmax(
            attn_scores / keys.shape[-1]**0.5, dim=-1
        )

        print("Attention Weights Before Dropout:\n", attn_weights)

        attn_weights = self.dropout(attn_weights) # New

        print("Attention Weights After Dropout:\n", attn_weights)

        context_vec = attn_weights @ values
        return context_vec

torch.manual_seed(123)
context_length = batch.shape[1]
ca = CausalAttention(d_in, d_out, context_length, 0.5)
context_vecs = ca(batch)
print("context_vecs.shape:", context_vecs.shape)


Attention Weights Before Dropout:
 tensor([[[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.5321, 0.4679, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.3616, 0.3185, 0.3198, 0.0000, 0.0000, 0.0000],
         [0.2627, 0.2408, 0.2413, 0.2552, 0.0000, 0.0000],
         [0.2046, 0.1921, 0.1926, 0.2020, 0.2088, 0.0000],
         [0.1759, 0.1582, 0.1586, 0.1690, 0.1747, 0.1637]],

        [[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.5321, 0.4679, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.3616, 0.3185, 0.3198, 0.0000, 0.0000, 0.0000],
         [0.2627, 0.2408, 0.2413, 0.2552, 0.0000, 0.0000],
         [0.2046, 0.1921, 0.1926, 0.2020, 0.2088, 0.0000],
         [0.1759, 0.1582, 0.1586, 0.1690, 0.1747, 0.1637]]],
       grad_fn=<SoftmaxBackward0>)
Attention Weights After Dropout:
 tensor([[[2.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.9359, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.7232, 0.6371, 0.0000, 0.0000, 0.0000, 0.0000],
       

<div class="alert alert-block alert-info">

As we can see, the resulting context vector is a 3D tensor where each token is now represented by a 2D
embedding:
    
</div>

<div class="alert alert-block alert-warning">

In the next section, we will expand on this concept
and implement a multi-head attention module, that implements several of such causal
attention mechanisms in parallel.

</div>